blank_issues_enabled: true
contact_links:
- name: if you have Docker Desktop on Linux installed
    url: https://github.com/docker/desktop-linux/issues
    about: Please report any bug report or feature request to the Docker Desktop for Linux team.

  - name: Alternatively, refer to The Moby Project
    url: https://github.com/moby/moby/issues
    about: Please report any bug or feature request to the Moby Project.
